require conf/distro/include/dumpling.inc
require conf/distro/include/tq-provider-ti.inc

DISTRO = "dumpling-wayland-ti"
DISTRO_NAME = "Dumpling Wayland (TQ-Systems Dumpling Wayland Distribution for TI BSP)"
