require conf/distro/include/dumpling.inc
require conf/distro/include/tq-provider-ls.inc

DISTRO = "dumpling-ls"
DISTRO_NAME = "Dumpling (TQ-Systems Dumpling Distribution) for TQ-Systems Layerscape BSP"
