require conf/distro/include/spaetzle.inc
require conf/distro/include/tq-provider-ls.inc

DISTRO = "spaetzle-ls"
DISTRO_NAME = "Spaetzle (TQ-Systems Spaetzle Distribution) for TQ-Systems Layerscape BSP"
