# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "dumpling"
BBFILE_PATTERN_dumpling = "^${LAYERDIR}/"
BBFILE_PRIORITY_dumpling = "7"

LAYERDEPENDS_dumpling = "core openembedded-layer tq-layer"
LAYERSERIES_COMPAT_dumpling = "wrynose"

BBFILES_DYNAMIC += "\
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/recipes-*/*/*.bbappend \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/recipes-*/*/*.bb \
    freescale-layer:${LAYERDIR}/dynamic-layers/freescale-layer/recipes-*/*/*.bbappend \
    freescale-layer:${LAYERDIR}/dynamic-layers/freescale-layer/recipes-*/*/*.bb \
    qt6-layer:${LAYERDIR}/dynamic-layers/qt6-layer/recipes-*/*/*.bbappend \
    qt6-layer:${LAYERDIR}/dynamic-layers/qt6-layer/recipes-*/*/*.bb \
    rauc:${LAYERDIR}/dynamic-layers/rauc/recipes-*/*/*.bbappend \
    rauc:${LAYERDIR}/dynamic-layers/rauc/recipes-*/*/*.bb \
"

# keep LAYERRECOMMENDS in sync with dynamic layers
# to prevent parsing errors from layer index
LAYERRECOMMENDS_tq-layer = "\
    chromium-browser-layer \
    freescale-layer \
    qt6-layer \
    rauc \
"

DUMPLING_LAYERDIR := "${LAYERDIR}"
