IMX_DEFAULT_BSP = "nxp"

PREFERRED_PROVIDER_virtual/kernel_tqma6x = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma6ulx = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma6ullx = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma7x = "linux-imx-tq"

PREFERRED_PROVIDER_virtual/kernel_tqma8x = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma8xx = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma8xxs = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma8mx = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma8mxml = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma8mxnl = "linux-imx-tq"
PREFERRED_PROVIDER_virtual/kernel_tqma8mpxl = "linux-imx-tq"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-imx-tq"
