#@TYPE: Machine
#@NAME: i.MX95 TQMa95xxSA on MB-SMARC-2
#@DESCRIPTION: TQ-Systems GmbH i.MX95 MB-SMARC-2 Kit
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>

require conf/machine/include/tqma95xxsa-mb-smarc-2.inc

OEI_RAM_SIZE = "2"
SYSTEM_MANAGER_CONFIG ?= "tqm95_s02g0c000"

UBOOT_CONFIG[sd] = "tqma95xxsa_2gb_mb_smarc_2_defconfig"
UBOOT_CONFIG_IMAGE_FSTYPES[sd] = "wic"
