#@TYPE: Machine
#@NAME: i.MX 8MP TQMa8MP[Q,D,S[L]]L on MBa8MPxL
#@DESCRIPTION: i.MX 8MP MBa8MPxL starter kit and computing board
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>
#
# Processor                     Memory     Configuration
# --------------                ------     --------------------------------------
# i.MX8MP[Q,D,S][L]             1,2,8 GiB  tqma8mpxl_multi_mba8mpxl_[ecc,uuu]defconfig

require conf/machine/include/tqma8mpxl.inc
require conf/machine/include/mba8-common.inc

WKS_FILE = "tqmaxx-imx-v8-sdimg${@bb.utils.contains('DISTRO_FEATURES', 'rauc', '-rauc-ab', '', d)}.wks.in"

# Set u-boot DTB, needed for boot image construction
UBOOT_DTB_NAME = "imx8mp-tqma8mpql-mba8mpxl.dtb"

KERNEL_DEVICETREE = "\
    freescale/imx8mp-tqma8mpql-mba8mpxl.dtb \
    freescale/imx8mp-tqma8mpql-mba8mpxl-lvds-g133han01.dtb \
    freescale/imx8mp-tqma8mpql-mba8mpxl-lvds.dtbo \
    freescale/imx8mp-tqma8mpql-mba8mpxl-lvds-g133han01.dtbo \
"

KERNEL_DEVICETREE_linux-imx-tq = "\
    freescale/imx8mp-tqma8mpql-mba8mpxl-imx327.dtb \
    freescale/imx8mp-tqma8mpql-mba8mpxl-lvds-tm070jvhg33.dtb \
    freescale/imx8mp-tqma8mpql-mba8mpxl-ov9281.dtb \
    freescale/imx8mp-tqma8mpql-mba8mpxl-rpmsg.dtb \
    freescale/imx8mp-tqma8mpql-mba8mpxl-imx327.dtbo \
    freescale/imx8mp-tqma8mpql-mba8mpxl-ov9281.dtbo \
    freescale/imx8mp-tqma8mpql-mba8mpxl-rpmsg.dtbo \
"

KERNEL_DEVICETREE_linux-tq = "\
    freescale/imx8mp-tqma8mpql-mba8mpxl-lvds.dtb \
"

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)}"

UBOOT_CONFIG ??= "\
    ecc \
    mfgtool \
    sd \
"

UBOOT_CONFIG[ecc] = "tqma8mpxl_multi_mba8mpxl_ecc_defconfig"
UBOOT_CONFIG[sd] = "tqma8mpxl_multi_mba8mpxl_defconfig,wic"
UBOOT_CONFIG[mfgtool] = "tqma8mpxl_multi_mba8mpxl_uuu_defconfig"

MACHINE_FEATURES += "\
    bluetooth \
    camera \
    screen \
    touchscreen \
    wifi \
"

MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'wifi', 'linux-firmware-ath10k', '', d)}"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'bluetooth', 'linux-firmware-qca', '', d)}"

# Add packages we want to be deployed, even when they are not part of rootfs
# We need these here to support UBI / NFS boot case
EXTRA_IMAGEDEPENDS += "\
    virtual/imx-cortexm-demos \
"

# Set Serial console @ UART4
SERIAL_CONSOLES = "115200;ttymxc3"
# recipe imx-atf-tq: boot / debug UART address for UART4
ATF_IMX_BOOT_UART_BASE ?= "0x30a60000"

# disable virtual console support for this board and limit getty to SERIAL_CONSOLES only
USE_VT = "0"

CORTEXM_DEMOS += "\
    hello_world.bin \
    rpmsg_lite_pingpong_rtos_linux_remote.bin \
"

IMAGE_BOOT_FILES = "\
    ${@create_image_boot_dtb_files(d)} \
    ${CORTEXM_DEMOS} \
    ${KERNEL_IMAGETYPE} \
"

# SD boot image and FlexSPI boot image can be built using same U-Boot config
IMXBOOT_TARGETS ?= "\
    flash_evk_flexspi \
    flash_spl_uboot \
"

#
# bootstream name, construction see imx-boot recipe, do_deploy
#
MACHINE_WKS_BOOTSTREAM ?= "imx-boot-${MACHINE}-sd.bin-flash_spl_uboot"

# build additional fitImage
KERNEL_IMAGETYPES = "${@bb.utils.contains('DISTRO_FEATURES', 'tiny', '${KERNEL_IMAGETYPE}', '${KERNEL_IMAGETYPE} fitImage', d)}"
KERNEL_CLASSES += "kernel-fitimage"

#
# TODO: revisit memory layout for optee support
#
# fitImage Settings:
# Kernel image offset in RAM:               64 MiB
# reserved space for uncompressed kernel:   48 MiB
# fdt/dtb offset in RAM:                    112 MiB
# dtbo offset in RAM:                       113 MiB
# init(rd) offset in RAM:                   128 MiB
UBOOT_ENTRYPOINT:mx8m-generic-bsp = "0x44000000"
UBOOT_LOADADDRESS:mx8m-generic-bsp = "0x44000000"
UBOOT_DTB_LOADADDRESS:mx8m-generic-bsp = "0x47000000"
UBOOT_DTBO_LOADADDRESS:mx8m-generic-bsp = "0x4710000"
UBOOT_RD_LOADADDRESS:mx8m-generic-bsp = "0x48000000"
UBOOT_RD_ENTRYPOINT:mx8m-generic-bsp = "0x48000000"
