#@TYPE: Machine
#@NAME: i.MX93 TQMa93xxLA (ADAP) and TQMa93xxCA on MBa91xxCA
#@DESCRIPTION: TQ-Systems GmbH i.MX93 MBa91xxCA starter kit
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>

require conf/machine/include/tqma93xx.inc
require conf/machine/include/mba91xx-common.inc

MACHINE_FEATURES += "\
    lte \
"

UBOOT_CONFIG ??= "\
    ecc \
    sd \
    uuu \
"

UBOOT_CONFIG[ecc] = "tqma93xx_mba91xxca_ecc_defconfig"
UBOOT_CONFIG[sd] = "tqma93xx_mba91xxca_defconfig"
UBOOT_CONFIG_IMAGE_FSTYPES[sd] = "wic"
UBOOT_CONFIG[uuu] = "tqma93xx_mba91xxca_uuu_defconfig"

KERNEL_DEVICETREE = "\
    freescale/imx93-tqma9352-mba91xxca.dtb \
"

KERNEL_DEVICETREE_linux-imx-tq = "\
    freescale/imx93-tqma9352-mba91xxca-rgb-cdtech-dc44.dtb \
    freescale/imx93-tqma9352-mba91xxca-lvds-tm070jvhg33.dtb \
    freescale/imx93-tqma9352-mba91xxca-rgb-cdtech-dc44.dtbo \
    freescale/imx93-tqma9352-mba91xxca-lvds-tm070jvhg33.dtbo \
"

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)}"

# Set the USB UART of the wwan card inserted into mini PCIe slot. Use this UART
# to send AT commands to the wwan card (see quectel-ppp recipe). This assignment
# must not contain spaces and line feeds.
QUECTEL_PPP_TTY = "/dev/serial/by-path/platform-ci_hdrc\.0-usb-0\:1\.2\:1\.2-port0"

# This example shows the APN to be used for NXTGN IoT SIM cards. Please uncomment
# and override with the the string needed for your provider.
# For further information see README in doc folder of this layer.
# QUECTEL_PPP_APN ?= "h.nxtgn"

#
# fitImage Settings:
# Kernel image offset in RAM:               16 MiB
# reserved space for uncompressed kernel:   48 MiB
# fdt/dtb offset in RAM:                    64 MiB
# dtbo offset in RAM:                       65 MiB
# init(rd) offset in RAM:                   80 MiB
# (loadaddr                                128 MiB)
# (kernel_addr_r                           256 MiB)
# (optee offset                       256 + 96 MiB)
# (optee size                               32 MiB)
UBOOT_ENTRYPOINT = "0x81000000"
UBOOT_LOADADDRESS = "0x81000000"
UBOOT_DTB_LOADADDRESS = "0x84000000"
UBOOT_DTBO_LOADADDRESS = "0x84100000"
UBOOT_RD_LOADADDRESS = "0x85000000"
UBOOT_RD_ENTRYPOINT = "0x85000000"

UBOOT_EXTLINUX_FDTDIR ?= ""

UBOOT_EXTLINUX_LABELS ?= " \
    default \
"

EXTRA_EXTLINUX_LABELS ?= ""

EXTRA_EXTLINUX_LABELS:mx93-nxp-bsp = " \
    lvds-tm070jvhg33 \
    rgb-cdtech-dc44 \
"

UBOOT_EXTLINUX_LABELS += "${EXTRA_EXTLINUX_LABELS}"

UBOOT_EXTLINUX_DEFAULT_LABEL ?= "default"
UBOOT_EXTLINUX_KERNEL_IMAGE_default = "../fitImage"
UBOOT_EXTLINUX_MENU_DESCRIPTION_default = "${DISTRO_NAME} on ${MACHINE} (default)"

UBOOT_EXTLINUX_KERNEL_IMAGE_lvds-tm070jvhg33 = \
    "../fitImage#${FIT_CONF_PREFIX}imx93-tqma9352-mba91xxca.dtb#${FIT_CONF_PREFIX}imx93-tqma9352-mba91xxca-lvds-tm070jvhg33.dtbo"
UBOOT_EXTLINUX_MENU_DESCRIPTION_lvds-tm070jvhg33 = \
    "${DISTRO_NAME} on ${MACHINE} (LVDS display: TM070JDVG33)"

UBOOT_EXTLINUX_KERNEL_IMAGE_rgb-cdtech-dc44 = \
    "../fitImage#${FIT_CONF_PREFIX}imx93-tqma9352-mba91xxca.dtb#${FIT_CONF_PREFIX}imx93-tqma9352-mba91xxca-rgb-cdtech-dc44.dtbo"
UBOOT_EXTLINUX_MENU_DESCRIPTION_rgb-cdtech-dc44 = \
    "${DISTRO_NAME} on ${MACHINE} (RGB display: CDTECH DC44)"

require conf/machine/include/tq-distroboot.inc
