#@TYPE: Machine
#@NAME: TQ-Systems GmbH TQMa7x Module with 512 / 1024 / 2048 MiB RAM on MBa7 Baseboard
#@SOC: i.MX7
#@DESCRIPTION: Machine configuration for TQ-Systems GmbH TQMa7 DUAL
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>

require conf/machine/include/tqma7.inc
require conf/machine/include/tq-machine.inc

SERIAL_CONSOLES = "115200;ttymxc5"

# disable virtual console support for this board and limit getty to SERIAL_CONSOLES only
USE_VT = "0"

KERNEL_DEVICETREE = "\
    nxp/imx/imx7d-mba7.dtb \
"

KERNEL_DEVICETREE_linux-tq = "\
    nxp/imx/imx7d-mba7-lvds-tm070jvhg33.dtb \
    nxp/imx/imx7d-mba7-rgb-cdtech-fc21.dtb \
    nxp/imx/imx7d-mba7-rgb-cdtech-dc44.dtb \
"

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)}"

MACHINE_FEATURES += "\
    bluetooth \
    screen \
    wifi \
"

MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'wifi', 'linux-firmware-ath10k', '', d)}"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'bluetooth', 'linux-firmware-qca', '', d)}"

WKS_FILE = "tqmaxx-imx-v7-sdimg.wks.in"

# allow to easy override for different configuration
MACHINE_WKS_BOOTSTREAM ?= "${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-sd"

UBOOT_CONFIG ?= "\
    sd qspi uuu\
    512mb_sd 512mb_qspi 512mb_uuu\
    1gb_sd 1gb_qspi 1gb_uuu\
    2gb_sd 2gb_qspi 2gb_uuu\
    "

UBOOT_CONFIG[sd] = "tqma7d_1gb_mba7_mmc_defconfig"
UBOOT_CONFIG[qspi] = "tqma7d_1gb_mba7_qspi_defconfig"
UBOOT_CONFIG[uuu] = "tqma7d_1gb_mba7_mfg_defconfig"

UBOOT_CONFIG[2gb_sd] = "tqma7d_2gb_mba7_mmc_defconfig"
UBOOT_CONFIG[2gb_qspi] = "tqma7d_2gb_mba7_qspi_defconfig"
UBOOT_CONFIG[2gb_uuu] = "tqma7d_2gb_mba7_mfg_defconfig"

UBOOT_CONFIG[1gb_sd] = "tqma7d_1gb_mba7_mmc_defconfig"
UBOOT_CONFIG[1gb_qspi] = "tqma7d_1gb_mba7_qspi_defconfig"
UBOOT_CONFIG[1gb_uuu] = "tqma7d_1gb_mba7_mfg_defconfig"

UBOOT_CONFIG[512mb_sd] = "tqma7d_512mb_mba7_mmc_defconfig"
UBOOT_CONFIG[512mb_qspi] = "tqma7d_512mb_mba7_qspi_defconfig"
UBOOT_CONFIG[512mb_uuu] = "tqma7d_512mb_mba7_mfg_defconfig"

# allow creating multiple wic images for a single machine
IMAGE_CLASSES += "gen_additional_wic"
# Workaround for gen_additional_wic, remove after conversion / compression is handled in class
TQ_IMAGE_COMPRESSION = ""

EXTWIC_BOOTLOADER_IMAGES = "\
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-512mb_sd \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-1gb_sd \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-2gb_sd \
"
