#@TYPE: Machine
#@NAME: TQ-Systems TQMa67xx Module on MBa67xx Baseboard (AM67xx R5)
#@SOC: AM67xx
#@DESCRIPTION: Machine configuration for TQ-Systems TQMa67xx (Cortex-R5 toolchain)
#@MAINTAINER: Nora Schiffer <oss@ew.tq-group.com>

require conf/machine/include/tqma67xx-k3r5.inc

UBOOT_MACHINE = "tqma67xx_mba67xx_r5_defconfig"
