#@TYPE: Machine
#@NAME: TQ-Systems GmbH TQMa7x Module with 512 / 1024 / 2048 MiB RAM on MBa7 Baseboard
#@SOC: i.MX7
#@DESCRIPTION: Machine configuration for TQ-Systems GmbH TQMa7 DUAL
#@MAINTAINER: Markus Niebel  <oss@ew.tq-group.com>

include conf/machine/include/tqma7x-mba7.inc

UBOOT_CONFIG ?= "\
    sd qspi \
    512mb_sd 512mb_qspi \
    1gb_sd 1gb_qspi \
    2gb_sd 2gb_qspi \
    "

UBOOT_CONFIG[sd] = "tqma7d_mba7_mmc_1gb_defconfig"
UBOOT_CONFIG[qspi] = "tqma7d_mba7_qspi_1gb_defconfig"

UBOOT_CONFIG[2gb_sd] = "tqma7d_mba7_mmc_2gb_defconfig"
UBOOT_CONFIG[2gb_qspi] = "tqma7d_mba7_qspi_2gb_defconfig"

UBOOT_CONFIG[1gb_sd] = "tqma7d_mba7_mmc_1gb_defconfig"
UBOOT_CONFIG[1gb_qspi] = "tqma7d_mba7_qspi_1gb_defconfig"

UBOOT_CONFIG[512mb_sd] = "tqma7d_mba7_mmc_512mb_defconfig"
UBOOT_CONFIG[512mb_qspi] = "tqma7d_mba7_qspi_512mb_defconfig"

# allow creating multiple wic images for a single machine
IMAGE_CLASSES += "gen_additional_wic"

EXTWIC_BOOTLOADER_IMAGES = "\
    u-boot-${MACHINE}.imx-512mb_sd \
    u-boot-${MACHINE}.imx-1gb_sd \
    u-boot-${MACHINE}.imx-2gb_sd \
"
