#@TYPE: Machine
#@NAME: TQ-Systems GmbH TQMa6ULxL SOM on MBa6ULxL baseboard
#@SOC: i.MX6UL
#@DESCRIPTION: Machine configuration for TQ-Systems GmbH TQMaULxL on MBa6ULxL
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>
#
# By default, this machine be will build for the full featured option
# with SD / eMMC boot
#
# To build U-Boot for other CPU or memory combinations, you can set
# the UBOOT_MACHINE variable in your local.conf according to the
# following table:
#
# Processor     Memory         Boot device            Configuration
# ----------    -----------    ------------           ---------------------------------
# i.MX6UL       256/512 MiB    SD / e-MMC             tqma6ulxl_mba6ulxl_mmc_defconfig
# i.MX6UL       256/512 MiB    Serial Downloader      tqma6ulxl_mba6ulxl_mfg_defconfig
#

require conf/machine/include/tqma6ul.inc

SERIAL_CONSOLES = "115200;ttymxc0"

# disable virtual console support for this board and limit getty to SERIAL_CONSOLES only
USE_VT = "0"


KERNEL_DEVICETREE_linux-tq = "\
    nxp/imx/imx6ul-tqma6ul2l-mba6ulxl.dtb \
    nxp/imx/imx6ul-tqma6ul2l-mba6ulxl-glyn-etm0700g0edh6.dtb \
"

KERNEL_DEVICETREE += " ${@kernel_provider_dtbs(d)}"

# no sound on MBa6ULxL
MACHINE_FEATURES:remove = "alsa"

MACHINE_FEATURES += "\
    bluetooth \
    screen \
    wifi \
"

# install kernel and devicetree also under /boot inside the rootfs
MACHINE_EXTRA_RRECOMMENDS += "\
    kernel-devicetree \
    kernel-image \
"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'wifi', 'linux-firmware-ath10k', '', d)}"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'bluetooth', 'linux-firmware-qca', '', d)}"

WKS_FILE = "tqmaxx-imx-v7-sdimg.wks.in"

# allow to easy override for different configuration
MACHINE_WKS_BOOTSTREAM ?= "${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-sd"

UBOOT_CONFIG ?= "sd uuu"
UBOOT_CONFIG[sd] = "tqma6ulxl_mba6ulxl_mmc_defconfig,wic"
UBOOT_CONFIG[uuu] = "tqma6ulxl_mba6ulxl_mfg_defconfig"
