#@TYPE: Machine
#@NAME: i.MX 8MP TQMa8MP[Q,D,S[L]]S on MB-SMARC-2
#@DESCRIPTION: i.MX 8MP MB-SMARC-2 starter kit and computing board
#@MAINTAINER: Paul Gerber <oss@ew.tq-group.com>
#
# Processor                     Memory     Configuration
# --------------                ------     --------------------------------------
# i.MX8MP[Q,D,S][L]             1,2,8 GiB  tqma8mpxs_multi_mb_smarc_2_[uuu_]defconfig

require conf/machine/include/tqma8mpxs.inc
require conf/machine/include/mb-smarc-2-common.inc

WKS_FILE = "tqmaxx-imx-v8-sdimg${@bb.utils.contains('DISTRO_FEATURES', 'rauc', '-rauc-ab', '', d)}.wks.in"

# Set u-boot DTB, needed for boot image construction
UBOOT_DTB_NAME = "imx8mp-tqma8mpqs-mb-smarc-2.dtb"

KERNEL_DEVICETREE = "\
    freescale/imx8mp-tqma8mpqs-mb-smarc-2.dtb \
    freescale/imx8mp-tqma8mpqs-mb-smarc-2-lvds0-tm070jvhg33.dtb \
    freescale/imx8mp-tqma8mpqs-mb-smarc-2-lvds1-tm070jvhg33.dtb \
    freescale/imx8mp-tqma8mpqs-mb-smarc-2-lvds0-tm070jvhg33.dtbo \
    freescale/imx8mp-tqma8mpqs-mb-smarc-2-lvds1-tm070jvhg33.dtbo \
"

# TODO: add ECC defconfig in U-Boot
UBOOT_CONFIG ??= "\
    sd \
    mfgtool \
"

# TODO: add ECC defconfig in U-Boot
UBOOT_CONFIG[sd] = "tqma8mpxs_multi_mb_smarc_2_defconfig,wic"
UBOOT_CONFIG[mfgtool] = "tqma8mpxs_multi_mb_smarc_2_uuu_defconfig"

MACHINE_FEATURES += "\
    camera \
"

# Set Serial console @ UART3
SERIAL_CONSOLES = "115200;ttymxc2"
# recipe imx-atf-tq: boot / debug UART address for UART3
ATF_IMX_BOOT_UART_BASE ?= "0x30880000"

# disable virtual console support for this board and limit getty to SERIAL_CONSOLES only
USE_VT = "0"

UBOOT_EXTLINUX_FDTDIR ?= ""

UBOOT_EXTLINUX_LABELS ?= " \
    default \
"

EXTRA_EXTLINUX_LABELS ?= ""

EXTRA_EXTLINUX_LABELS:mx8mp-mainline-bsp = " \
    lvds0 \
    lvds1 \
"

UBOOT_EXTLINUX_LABELS += "${EXTRA_EXTLINUX_LABELS}"

UBOOT_EXTLINUX_DEFAULT_LABEL ?= "default"
UBOOT_EXTLINUX_KERNEL_IMAGE_default = "../fitImage"
UBOOT_EXTLINUX_MENU_DESCRIPTION_default = "${DISTRO_NAME} on ${MACHINE} (default)"

# TODO: upstream name change is pending, to be removed once name change is backported
UBOOT_EXTLINUX_KERNEL_IMAGE_lvds0 = \
    "../fitImage#${FIT_CONF_PREFIX}imx8mp-tqma8mpqs-mb-smarc-2.dtb#${FIT_CONF_PREFIX}imx8mp-tqma8mpqs-mb-smarc-2-lvds0-tm070jvhg33.dtbo"
UBOOT_EXTLINUX_MENU_DESCRIPTION_lvds0 = \
    "${DISTRO_NAME} on ${MACHINE} (LVDS display on LVDS0: TM070JVHG33)"

UBOOT_EXTLINUX_KERNEL_IMAGE_lvds1 = \
    "../fitImage#${FIT_CONF_PREFIX}imx8mp-tqma8mpqs-mb-smarc-2.dtb#${FIT_CONF_PREFIX}imx8mp-tqma8mpqs-mb-smarc-2-lvds1-tm070jvhg33.dtbo"
UBOOT_EXTLINUX_MENU_DESCRIPTION_lvds1 = \
    "${DISTRO_NAME} on ${MACHINE} (LVDS display on LVDS1: TM070JVHG33)"

require conf/machine/include/tq-distroboot.inc
