#@TYPE: Machine
#@NAME: i.MX 8MN TQMa8MxNL (1 GiB) on MBa8Mx
#@DESCRIPTION: i.MX8MN MBa8Mx starter kit
#@MAINTAINER: Markus Niebel, Alexander Stein <oss@ew.tq-group.com>
#
# Processor                     Memory    Configuration
# --------------                ------    --------------------------------------
# i.MX8MN                       1GB       tqma8mxnl_1gb_mba8mx_defconfig

require conf/machine/include/tqma8mxnl.inc
require conf/machine/include/mba8mx-common.inc

KERNEL_DEVICETREE = "\
    freescale/imx8mn-tqma8mqnl-mba8mx.dtb \
"

KERNEL_DEVICETREE_linux-imx-tq = "\
    freescale/imx8mn-tqma8mqnl-mba8mx-lcdif-lvds-tm070jvhg33.dtb \
    freescale/imx8mn-tqma8mqnl-mba8mx-lcdif-lvds-tm070jvhg33-imx327.dtb \
    freescale/imx8mn-tqma8mqnl-mba8mx-lcdif-lvds-tm070jvhg33-ov9281.dtb \
    freescale/imx8mn-tqma8mqnl-mba8mx-rpmsg.dtb \
    freescale/imx8mn-tqma8mqnl-mba8mx-usb0otg.dtb \
"

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)}"

IMAGE_BOOT_FILES += "${@create_image_boot_dtb_files(d)}"

UBOOT_CONFIG ??= "\
    sd \
    uuu \
"

UBOOT_CONFIG[sd] = "tqma8mxnl_1gb_mba8mx_defconfig"
UBOOT_CONFIG_IMAGE_FSTYPES[sd] = "wic"
UBOOT_CONFIG[uuu] = "tqma8mxnl_1gb_mba8mx_mfg_defconfig"

#
# TODO: revisit memory layout for optee support
#
# fitImage Settings:
# Kernel image offset in RAM:               64 MiB
# reserved space for uncompressed kernel:   48 MiB
# fdt/dtb offset in RAM:                    112 MiB
# dtbo offset in RAM:                       113 MiB
# init(rd) offset in RAM:                   128 MiB
UBOOT_ENTRYPOINT:mx8m-generic-bsp = "0x44000000"
UBOOT_LOADADDRESS:mx8m-generic-bsp = "0x44000000"
UBOOT_DTB_LOADADDRESS:mx8m-generic-bsp = "0x47000000"
UBOOT_DTBO_LOADADDRESS:mx8m-generic-bsp = "0x47100000"
UBOOT_RD_LOADADDRESS:mx8m-generic-bsp = "0x48000000"
UBOOT_RD_ENTRYPOINT:mx8m-generic-bsp = "0x48000000"
