#@TYPE: Machine
#@NAME: i.MX 8MP TQMa8MP[Q,D,S[L]]L on MBa8MPxL
#@DESCRIPTION: i.MX 8MP MBa8MPxL starter kit and computing board
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>
#
# Processor                     Memory     Configuration
# --------------                ------     --------------------------------------
# i.MX8MP[Q,D,S][L]             1,2,8 GiB  tqma8mpxl_multi_mba8mpxl_defconfig
# i.MX8MP[Q,D,S][L]             2 GiB      tqma8mpxl_2gb_mba8mpxl_defconfig

require conf/machine/include/tqma8mpxl-mba8mpxl.inc

UBOOT_CONFIG ??= "\
    ecc \
    mfgtool \
    sd \
"

UBOOT_CONFIG[ecc] = "tqma8mpxl_multi_mba8mpxl_ecc_defconfig"
UBOOT_CONFIG[sd] = "tqma8mpxl_multi_mba8mpxl_defconfig,wic"
UBOOT_CONFIG[mfgtool] = "tqma8mpxl_multi_mba8mpxl_uuu_defconfig"

# build additional fitImage
KERNEL_IMAGETYPES = "${@bb.utils.contains('DISTRO_FEATURES', 'tiny', '${KERNEL_IMAGETYPE}', '${KERNEL_IMAGETYPE} fitImage', d)}"
KERNEL_CLASSES += "kernel-fitimage"

#
# TODO: revisit memory layout for optee support
#
# fitImage Settings:
# Kernel image offset in RAM:               64 MiB
# reserved space for uncompressed kernel:   48 MiB
# fdt/dtb offset in RAM:                    112 MiB
# dtbo offset in RAM:                       113 MiB
# init(rd) offset in RAM:                   128 MiB
UBOOT_ENTRYPOINT:mx8m-generic-bsp = "0x44000000"
UBOOT_LOADADDRESS:mx8m-generic-bsp = "0x44000000"
UBOOT_DTB_LOADADDRESS:mx8m-generic-bsp = "0x47000000"
UBOOT_DTBO_LOADADDRESS:mx8m-generic-bsp = "0x4710000"
UBOOT_RD_LOADADDRESS:mx8m-generic-bsp = "0x48000000"
UBOOT_RD_ENTRYPOINT:mx8m-generic-bsp = "0x48000000"
