#@TYPE: Machine
#@NAME: TQ-Systems GmbH TQMa6ULLx[L] SOM with 256 / 512 MB RAM on MBa6ULx baseboard
#@SOC: i.MX6ULL
#@DESCRIPTION: Machine configuration for TQ-Systems GmbH TQMaULLx[L]
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>

include conf/machine/include/tqma6ull.inc
include conf/machine/include/mba6ulx-common.inc

KERNEL_DEVICETREE = "\
    nxp/imx/imx6ull-tqma6ull2-mba6ulx.dtb \
    nxp/imx/imx6ull-tqma6ull2l-mba6ulx.dtb \
"

KERNEL_DEVICETREE_linux-tq = "\
    nxp/imx/imx6ull-tqma6ull2-mba6ulx-cdtech-dc44.dtb \
    nxp/imx/imx6ull-tqma6ull2-mba6ulx-cdtech-fc21.dtb \
    nxp/imx/imx6ull-tqma6ull2-mba6ulx-lvds.dtb \
    nxp/imx/imx6ull-tqma6ull2l-mba6ulx-cdtech-dc44.dtb \
    nxp/imx/imx6ull-tqma6ull2l-mba6ulx-cdtech-fc21.dtb \
    nxp/imx/imx6ull-tqma6ull2l-mba6ulx-lvds.dtb \
"

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)}"

UBOOT_CONFIG ?= "\
    sd qspi uuu \
    sd_lga qspi_lga uuu_lga \
"

UBOOT_CONFIG[sd] = "tqma6ullx_mba6ul_mmc_defconfig,wic"
UBOOT_CONFIG[qspi] = "tqma6ullx_mba6ul_qspi_defconfig"
UBOOT_CONFIG[uuu] = "tqma6ullx_mba6ul_mfg_defconfig"

UBOOT_CONFIG[sd_lga] = "tqma6ullxl_mba6ul_mmc_defconfig"
UBOOT_CONFIG[qspi_lga] = "tqma6ullxl_mba6ul_qspi_defconfig"
UBOOT_CONFIG[uuu_lga] = "tqma6ullxl_mba6ul_mfg_defconfig"

# allow creating multiple wic images for a single machine
IMAGE_CLASSES += "gen_additional_wic"
# Workaround for gen_additional_wic, remove after conversion / compression is handled in class
TQ_IMAGE_COMPRESSION = ""

EXTWIC_BOOTLOADER_IMAGES = "\
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-sd \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-sd_lga \
"
