#@TYPE: Machine
#@NAME: i.MX95 TQMa95xxLA on MBa95xxCA
#@DESCRIPTION: TQ-Systems GmbH i.MX95 MBa95xxCA Kit
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>

require conf/machine/include/tqma95xxla.inc
require conf/machine/include/mba95xxca-common.inc

OEI_RAM_SIZE = "4"
SYSTEM_MANAGER_CONFIG ?= "tqm95_l04g0c000"

UBOOT_CONFIG[sd] = "tqma95xxla_4gb_mba95xxca_defconfig"
