#@TYPE: Machine
#@NAME: TQ-Systems GmbH TQMa6x SOM with on MBa6ULx baseboard, variants TQMa6S, TQMa6DL (1/2GB RAM), TQMa6D/Q  (1/2GB RAM), TQMa6DP/QP 
#@SOC: i.MX6S / i.MX6DL / i.MX6D / i.MX6Q / i.MX6DP / i.MX6QP
#@DESCRIPTION: Machine configuration for TQ-Systems GmbH TQMa6x
#@MAINTAINER: Markus Niebel <oss@ew.tq-group.com>

MACHINEOVERRIDES =. "imx:mx6q:mx6dl:"

require conf/machine/include/tqma6x.inc
require conf/machine/include/tq-machine.inc

SERIAL_CONSOLES = "115200;ttymxc1"

# disable virtual console support for this board and limit getty to SERIAL_CONSOLES only
USE_VT = "0"


KERNEL_DEVICETREE = "\
    imx6dl-mba6a.dtb \
    imx6dl-mba6a-duallvds-tm070jvhg33.dtb \
    imx6dl-mba6a-hdmi.dtb \
    imx6dl-mba6a-lvds-tm070jvhg33.dtb \
    \
    imx6dl-mba6b.dtb \
    imx6dl-mba6b-duallvds-tm070jvhg33.dtb \
    imx6dl-mba6b-hdmi.dtb \
    imx6dl-mba6b-lvds-tm070jvhg33.dtb \
    \
    imx6q-mba6a.dtb \
    imx6q-mba6a-duallvds-tm070jvhg33.dtb \
    imx6q-mba6a-hdmi.dtb \
    imx6q-mba6a-lvds-tm070jvhg33.dtb \
    \
    imx6q-mba6b.dtb \
    imx6q-mba6b-duallvds-tm070jvhg33.dtb \
    imx6q-mba6b-hdmi.dtb \
    imx6q-mba6b-lvds-tm070jvhg33.dtb \
    \
    imx6qp-mba6b.dtb \
    imx6qp-mba6b-duallvds-tm070jvhg33.dtb \
    imx6qp-mba6b-hdmi.dtb \
    imx6qp-mba6b-lvds-tm070jvhg33.dtb \
"

KERNEL_DEVICETREE_linux-tq = "\
    imx6dl-mba6a-cdtech-dc44.dtb \
    imx6dl-mba6a-cdtech-fc21.dtb \
    imx6dl-mba6a-lvds-g133han01.dtb \
    imx6dl-mba6a-multi.dtb \
    \
    imx6dl-mba6b-cdtech-dc44.dtb \
    imx6dl-mba6b-cdtech-fc21.dtb \
    imx6dl-mba6b-lvds-g133han01.dtb \
    imx6dl-mba6b-multi.dtb \
    \
    imx6q-mba6a-cdtech-dc44.dtb \
    imx6q-mba6a-cdtech-fc21.dtb \
    imx6q-mba6a-lvds-g133han01.dtb \
    imx6q-mba6a-multi.dtb \
    \
    imx6q-mba6b-cdtech-dc44.dtb \
    imx6q-mba6b-cdtech-fc21.dtb \
    imx6q-mba6b-lvds-g133han01.dtb \
    imx6q-mba6b-multi.dtb \
    \
    imx6qp-mba6b-cdtech-dc44.dtb \
    imx6qp-mba6b-cdtech-fc21.dtb \
    imx6qp-mba6b-lvds-g133han01.dtb \
    imx6qp-mba6b-multi.dtb \
"

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)} "

KERNEL_DEVICETREE += "${@kernel_provider_dtbs(d)}"

MACHINE_FEATURES += "\
    bluetooth \
    screen \
    touchscreen \
    wifi \
"

MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'wifi', 'linux-firmware-ath10k', '', d)}"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('COMBINED_FEATURES', 'bluetooth', 'linux-firmware-qca', '', d)}"

WKS_FILE = "tqmaxx-imx-v7-sdimg.wks.in"

# allow to easy override for different configuration
MACHINE_WKS_BOOTSTREAM ?= "${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-sd"

UBOOT_CONFIG ?= "\
    sd \
    tqma6s_512mb \
    tqma6dl_1024mb tqma6dl_2048mb \
    tqma6q_1024mb tqma6q_2048mb \
    tqma6qp_1024mb \
"

UBOOT_CONFIG[sd] = "tqma6qp_mba6_defconfig,wic"

UBOOT_CONFIG[tqma6s_512mb] = "tqma6s_mba6_defconfig"

UBOOT_CONFIG[tqma6dl_1024mb] = "tqma6dl_mba6_defconfig"
UBOOT_CONFIG[tqma6dl_2048mb] = "tqma6dl_2gb_mba6_defconfig"

UBOOT_CONFIG[tqma6q_1024mb] = "tqma6q_mba6_defconfig"
UBOOT_CONFIG[tqma6q_2048mb] = "tqma6q_2gb_mba6_defconfig"

UBOOT_CONFIG[tqma6qp_1024mb] = "tqma6qp_mba6_defconfig"

# allow creating multiple wic images for a single machine
IMAGE_CLASSES += "gen_additional_wic"
# Workaround for gen_additional_wic, remove after conversion / compression is handled in class
TQ_IMAGE_COMPRESSION = ""

EXTWIC_BOOTLOADER_IMAGES = "\
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-tqma6s_512mb \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-tqma6dl_1024mb \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-tqma6dl_2048mb \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-tqma6q_1024mb \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-tqma6q_2048mb \
    ${UBOOT_BINARY_BASENAME}-${MACHINE}.${UBOOT_SUFFIX}-tqma6qp_1024mb \
"

